Docker: Add a Docker secret for the Django key
We have decided against including an insecure default key with a mere
warning.  Therefore, unlike the admin and user secrets, the availability
of this secret is a hard requirement.  The instance will not be able to
start before a secret has been generated manually or by a management
tool.

diff --git a/server/docker/entrypoint b/server/docker/entrypoint
--- a/server/docker/entrypoint
+++ b/server/docker/entrypoint
@@ -2,6 +2,15 @@
 
 set -e
 
+# Set DJANGO_SECRET_KEY variable
+source /run/secrets/django
+[[ -n "$DJANGO_SECRET_KEY" ]] || {
+  echo "ERROR: Django secret key undefined!  Cannot continue."
+  sleep 5
+  exit 2
+}
+export SECRET_KEY="$DJANGO_SECRET_KEY"
+
 # TODO: env variable for this host
 wait-for-it -t 0 "server-db-setup:8000"
 
diff --git a/server/docker/entrypoint-db-setup b/server/docker/entrypoint-db-setup
--- a/server/docker/entrypoint-db-setup
+++ b/server/docker/entrypoint-db-setup
@@ -15,6 +15,15 @@ EOF
   sleep 10
 }
 
+# Set DJANGO_SECRET_KEY variable
+source /run/secrets/django
+[[ -n "$DJANGO_SECRET_KEY" ]] || {
+  echo "ERROR: Django secret key undefined!  Cannot continue."
+  sleep 5
+  exit 2
+}
+export SECRET_KEY="$DJANGO_SECRET_KEY"
+
 # Configure database
 # TODO: env variables??
 echo "postgres:5432:instancecfg:openslides:openslides" > "${HOME}/.pgpass"
